# You need libmamba solver for installation or mamba directly due to long modin installation
# https://modin.readthedocs.io/en/stable/getting_started/installation.html
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - scikit-learn-intelex==2023.1.1
  - kaggle==1.5.16
  - boto3==1.28.14
  - modin-all
  - unidist-mpi
  - polars
  - git>=2.0.0
  - pip:
    - xgboost==1.7.6
