name: Build
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code style
        run: |
          pip install -r requirements/linters.txt
          black . --check --diff
          flake8
          
      - name: Test with pytest
        run: |
          pip install -r requirements/tests.txt
          pytest
