name: Build
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code quality and run pytest
        run: |
          pip install -r requirements/dev_reqs.txt
          black . --check --diff
          flake8
          pytest
      - name: Make security report
        run: |
          bandit -c pyproject.toml -r . --format sarif --output bandit.sarif | true
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: bandit.sarif
      - name: Fail if issue with medium severity found
        run: |
          bandit -c pyproject.toml -r . -ll



  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9"]
        # This will be activated after https://github.com/intel-ai/timedf/issues/367
        exclude:
          - os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and run example_benchmark
        run: |
          python -m pip install --upgrade pip
          pip install .
          PANDAS_MODE="Pandas" benchmark-run example_benchmark -data_file "/datasets" -iterations 3
