name: Build
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code style and run pytest
        run: |
          pip install -r requirements/dev_reqs.txt
          black . --check --diff
          flake8
          pytest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install library and run sample benchmark with Pandas
        run: |
          pip install .
          PANDAS_MODE="Pandas" benchmark-run -b example_benchmark -data_file "/datasets"
    