name: Benchmarking
on:
  schedule:
    - cron: '51 1 * * *'
  workflow_dispatch:
    inputs:
      reset-cache:
        type: boolean
        default: true
  push:

jobs:
  modin-containerized:
    uses: ./.github/workflows/test-docker.yml
    with:
      name: modin-containerized
      reset-cache: ${{ !!inputs.reset-cache }}
    secrets:
      token: ${{ secrets.AMYACHEV_GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/build.yml

  modin-ray:
    needs: build
    uses: ./.github/workflows/test-conda-docker.yml
    with:
      test: modin-ray
      cache-suffix: ${{ needs.build.outputs.cache-suffix }}
      reset-cache: ${{ !!inputs.reset-cache }}

