name: Docker taxi test
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      reset-cache:
        type: boolean
        default: true
      build:
        type: string
        default: cpu

jobs:
  build:
    runs-on: [self-hosted, linux, intel-ai.omniscripts.modin-taxi]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          path: modin
          repository: modin-project/modin

      - uses: actions/checkout@v3
        with:
          path: hdk
          repository: intel-ai/hdk

      - name: Build docker image for modin tests
        run: |
          git rev-parse HEAD > .github/workflows/modin/omniscripts-git-rev
          tar --exclude=modin --exclude=build.tgz -cf .github/workflows/modin/omniscripts.tar .

          cd modin
          git rev-parse HEAD > ../.github/workflows/modin/git-rev
          tar -cf ../.github/workflows/modin/modin.tar modin/
          cd ..

          #mv build.tgz .github/workflows/modin/

          docker rm -f ci.${{ inputs.name }} || true
          docker build -t ci/${{ inputs.name }} -f .github/workflows/modin/Dockerfile.ci ${{ inputs.reset-cache && '--no-cache' || '' }} .github/workflows/modin

      - name: Run modin taxi microbenchmarks and upload results
        run:  |
          set -vx

          docker run --name ci.${{ inputs.name }} \
            ci/${{ inputs.name }} conda run -n modin bash /modin/taxi-runner.sh

      - name: Stop the container
        if: always()
        run: |
          docker stop ci.${{ inputs.name }} || true

